version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.9

executors:
  cibuilds:
    docker:
      - image: cibuilds/base:2019.06

workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              # Simplified SemVer regex
              only: /^\d+\.\d+\.\d+$/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^\d+\.\d+\.\d+$/
          context: orb-publishing

jobs:
  test:
    executor: cibuilds
    steps:
      - checkout
      - cli/install
      - run:
          name: "Validate Orb config"
          command: circleci orb validate orb.yml
  publish:
    executor: cli/default
    steps:
      - checkout
      - cli/install
      - cli/setup:
          token: CIRCLE_TOKEN
      - run:
          name: "Publish orb via the CircleCI CLI"
          command: circleci orb publish orb.yml versatile/openvpn3@${CIRCLE_TAG}
